### ISSUE TITLE
Simplify the app

### ISSUE THREAD

**Issue by justincy** [fs-webcomponents/sample-app#23]
The app is supposed to demonstrate how easy it is use the FS web components, but some parts of the app aren't very simple.

TODO:

* [x] https://github.com/fs-webcomponents/sample-app/issues/24 merge person-page and person-details
* [x] https://github.com/fs-webcomponents/sample-app/issues/22 move capr lookup to fs-add-person
* [x] https://github.com/fs-webcomponents/sample-app/issues/20 update person history

**Comment by justincy** [comment]
Related: https://github.com/fs-webcomponents/fs-elements/issues/8
